name: pass_env_var

on: [push]

env:  
  # ENV_VAR1: ${{ env.ENV_VAR }}
  ENV_VAR2: ${{ vars.ENV_VAR }}
  SECRET: ${{ secrets.SECRET }}

jobs:
  pass_env_var:
    runs-on: ubuntu-latest
    container: rocker/r-base:4.3.2
    steps:
      - uses: actions/checkout@v4

      - name: Pass secret to R script
        run: |
          echo "ENV_VAR1 is equal: $ENV_VAR1"
          echo "ENV_VAR2 is equal: $ENV_VAR2"
          echo "SECRET is equal: $SECRET"
          Rscript test_env_var_available.R

